#spring.application.name=gateway-app
server:
  port: 8084

debug: false


spring:
  application:
    name: gateway-app

# Gateway Routing
  cloud:
    gateway:
      mvc:
        routes:
          - id: company-micro-service
            #uri: http://localhost:8081  #for single service
            uri: lb://COMPANY-MICRO-SERVICE  #for Load balanced via service discovery
            predicates:
              - Path=/companies/**
          - id: job-micro-service
            #uri: http://localhost:8082
            uri: lb://JOB-MICRO-SERVICE
            predicates:
              - Path=/jobs/**
          - id: review-micro-service
            #uri: http://localhost:8083
            uri: lb://REVIEW-MICRO-SERVICE
            predicates:
              - Path=/reviews/**

          - id: eureka-service
            uri: http://service-registry:8761
            predicates:
              - Path=/eureka/home
            filters:
              - SetPath=/
          - id: eureka-service-static
            uri: http://service-registry:8761
            predicates:
              - Path=/eureka/**
# Eureka related
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://service-registry:8761/eureka/

# zipkin
management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans

