#spring.application.name=gateway-app
server:
  port: 8084

debug: true


spring:
  application:
    name: gateway-app

# Gateway Routing
  cloud:
    gateway:
      mvc:
        routes:
          - id: company-micro-service
            uri: http://localhost:8081
            predicates:
              - Path=/companies/**
          - id: job-micro-service
            uri: http://localhost:8082
            predicates:
              - Path=/jobs/**
          - id: review-micro-service
            uri: http://localhost:8083
            predicates:
              - Path=/reviews/**



# Eureka related
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

# zipkin
management:
  tracing:
    sampling:
      probability: 1.0


